# Jupyter Notebook

Site: [Jupyter](https://jupyter.org/)


![jupyter](img/jupyter.png)


-----------------

## Como instalar:
```bash
pip install jupyter
```


In [25]:
a = 10
b = 5
a + b

15

In [26]:
a/b

2.0

# NumPy

Site: [NumPy](https://numpy.org/)

-----------------

### Sintaxe amigável
### Mais rápido
### Facilidade de trabalhar com matrizes

-----------------


## Como instalar:
```bash
pip install numpy
```


In [27]:
import numpy

In [28]:
a = numpy.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
a = a.reshape(5,2)
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
b = numpy.random.randn(5,2)
b

array([[-0.48447952, -0.93052378],
       [-0.52467369, -0.1373841 ],
       [-0.26380462, -2.67002693],
       [-2.46547147, -0.13692522],
       [ 1.51307932,  0.96955492]])

In [31]:
c = numpy.random.randn(5,2)
c

array([[-0.71695381,  1.57641224],
       [-0.51831653, -0.11376325],
       [ 0.24796928,  0.40372492],
       [-0.42224998,  0.83046868],
       [-0.19087504,  1.02652266]])

In [32]:
b + c

array([[-1.20143333,  0.64588845],
       [-1.04299022, -0.25114735],
       [-0.01583534, -2.26630201],
       [-2.88772145,  0.69354346],
       [ 1.32220428,  1.99607759]])

In [35]:
numpy.mean(b, axis=1)

array([-0.70750165, -0.3310289 , -1.46691578, -1.30119835,  1.24131712])

In [34]:
numpy.std(b, axis=0)

array([1.26151638, 1.20701437])

In [36]:
b.transpose()

array([[-0.48447952, -0.52467369, -0.26380462, -2.46547147,  1.51307932],
       [-0.93052378, -0.1373841 , -2.67002693, -0.13692522,  0.96955492]])

In [15]:
b[:, 0]

array([ 1.45848698,  1.11459271, -0.7599088 , -0.94332714,  0.93837767])

# Pandas
Site: [Pandas](https://pandas.pydata.org/)


-----------------

### Ferramenta para análise de dados

-----------------


## Como instalar:
```bash
pip install pandas
```

In [38]:
import pandas

In [39]:
df = pandas.read_csv('data/train.csv')

In [40]:
samples = df.sample(10)
samples

title label_quality  \
1888  Parlante Panasonic Sc Ua7 Rojo Torre Inalambri...      reliable   
7101                         Gimnasio Funcional Raiders      reliable   
3563                      Botines Botitas Futbol Oferta      reliable   
3517  Aparelho Celular Lg Mg377a Completo Manual Fon...      reliable   
7493                     Aaa*4 Panasonic R03ual Blyster      reliable   
1273  Retentor Do Comando De Valvulas 2.0 8v 87-97 M...      reliable   
8758        Pedal Mxr M120 Auto Q Wah Envelope Filter -      reliable   
8025  Bandeja Dianteira Esquerda Vw Golf 2003  1j040...      reliable   
1415                 Maquillaje Idi Soft Matte Oil Free      reliable   
9344               Pecera 50x27x30 Encuadrada En Hierro      reliable   

        language                            category  
1888     spanish              MINI_COMPONENT_SYSTEMS  
7101     spanish                 UNIVERSAL_HOME_GYMS  
3563     spanish                      FOOTBALL_SHOES  
3517  portuguese                          CELLPHONES  
7493     spanish                      CELL_BATTERIES  
1273  portuguese      ENGINE_VALVES_SPRING_RETAINERS  
8758  portuguese                       PEDAL_EFFECTS  
8025  portuguese  AUTOMOTIVE_SUSPENSION_CONTROL_ARMS  
1415     spanish                         FOUNDATIONS  
9344     spanish                          FISH_TANKS

In [41]:
samples[samples.language == 'spanish']

title label_quality  \
1888  Parlante Panasonic Sc Ua7 Rojo Torre Inalambri...      reliable   
7101                         Gimnasio Funcional Raiders      reliable   
3563                      Botines Botitas Futbol Oferta      reliable   
7493                     Aaa*4 Panasonic R03ual Blyster      reliable   
1415                 Maquillaje Idi Soft Matte Oil Free      reliable   
9344               Pecera 50x27x30 Encuadrada En Hierro      reliable   

     language                category  
1888  spanish  MINI_COMPONENT_SYSTEMS  
7101  spanish     UNIVERSAL_HOME_GYMS  
3563  spanish          FOOTBALL_SHOES  
7493  spanish          CELL_BATTERIES  
1415  spanish             FOUNDATIONS  
9344  spanish              FISH_TANKS